"""ingest — fetch raw releases and store them content-addressed by sha256."""

from .base import (
    EXTRACTION_SUFFIX,
    SIDECAR_SUFFIX,
    ExtractionArtifact,
    FetchOutcome,
    Fetcher,
    RawDoc,
    RawRef,
    SidecarCollision,
    SourceRef,
    extraction_artifact_path,
    sidecar_doc_id,
    read_extraction_artifacts,
    read_raw_docs,
    store_raw,
    write_extraction_artifact,
    write_sidecar,
)
from .fetch import FetchedDoc, FetchError, fetch_url, looks_like_pdf
from .foundry import FoundryFetcher
from .pipeline import (
    ADVISORY_DOC_TYPES,
    ForgetReport,
    IngestReport,
    forget,
    identity_doc_id,
    ingest_file,
    run_ingest,
    url_doc_id,
)

__all__ = [
    "EXTRACTION_SUFFIX",
    "SIDECAR_SUFFIX",
    "ExtractionArtifact",
    "FetchOutcome",
    "Fetcher",
    "RawDoc",
    "RawRef",
    "SidecarCollision",
    "SourceRef",
    "extraction_artifact_path",
    "sidecar_doc_id",
    "read_extraction_artifacts",
    "read_raw_docs",
    "store_raw",
    "write_extraction_artifact",
    "write_sidecar",
    "FetchedDoc",
    "FetchError",
    "fetch_url",
    "looks_like_pdf",
    "FoundryFetcher",
    "ForgetReport",
    "IngestReport",
    "ADVISORY_DOC_TYPES",
    "forget",
    "identity_doc_id",
    "ingest_file",
    "run_ingest",
    "url_doc_id",
]
